# GitHub Action from: https://github.com/gaurav-nelson/github-action-markdown-link-check
# Uses code from: https://github.com/tcort/markdown-link-check
name: Check Markdown Links

on: 
  push:
  schedule:
    # Run monthly 
    # GitHub actions uses UTC for time zone
    # crontab format: minute hour day-of-month month day-of-week
    - cron: "17 4 4 * *"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        base-branch: main
        use-verbose-mode: yes
            